name: tdd_action

on: 
  push:
jobs:
  ejecutar_tests:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Hacer checkout del código
      - name: Checkout repository
        uses: actions/checkout@v5
      
      # Paso 2: Configurar Python
      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      
      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Paso 4: Ejecutar los tests
      - name: Run tests
        run: |
          pytest -v
